/* ===========================================================
   CID-10 — lista ampla focada em neurologia clínica.
   Cobre capítulos completos: F (mental), G (sistema nervoso).
   Cobertura ampla em I (cerebrovascular), M (dores), R (sintomas),
   S (trauma SN), H (neuro-oftalmo), Z (observação) e códigos
   correlatos (endócrinos, infecciosos, oncológicos do SNC).
=========================================================== */
window.CID10 = [
  // --- Infecciosas (relevantes em neuro) -------------------
  ['A39.0', 'Meningite meningocócica'],
  ['A39.2', 'Meningococemia aguda'],
  ['A80.9', 'Poliomielite aguda, não especificada'],
  ['A81.0', 'Doença de Creutzfeldt-Jakob'],
  ['A81.1', 'Panencefalite esclerosante subaguda'],
  ['A81.2', 'Leucoencefalopatia multifocal progressiva'],
  ['A81.9', 'Infecção por vírus atípico do SNC, não especificada'],
  ['A85.0', 'Encefalite por enterovírus'],
  ['A85.1', 'Encefalite por adenovírus'],
  ['A85.2', 'Encefalite viral transmitida por artrópodes'],
  ['A85.8', 'Outras encefalites virais especificadas'],
  ['A86',   'Encefalite viral, não especificada'],
  ['A87.0', 'Meningite por enterovírus'],
  ['A87.1', 'Meningite por adenovírus'],
  ['A87.9', 'Meningite viral, não especificada'],
  ['A88.0', 'Febre exantemática por enterovírus'],
  ['A89',   'Infecção viral do SNC, não especificada'],
  ['A92.3', 'Doença de Nilo Ocidental'],
  ['B00.4', 'Encefalite por herpesvírus'],
  ['B01.1', 'Encefalite por varicela'],
  ['B02.0', 'Encefalite por herpes-zoster'],
  ['B02.2', 'Herpes-zoster com outros sintomas neurológicos'],
  ['B05.0', 'Sarampo complicado por encefalite'],
  ['B06.0', 'Rubéola com complicações neurológicas'],
  ['B26.2', 'Encefalite caxumbática'],
  ['B58.2', 'Toxoplasmose cerebral'],

  // --- Neoplasias do SNC -----------------------------------
  ['C70.0', 'Neoplasia maligna das meninges cerebrais'],
  ['C70.1', 'Neoplasia maligna das meninges espinhais'],
  ['C70.9', 'Neoplasia maligna das meninges, não especificada'],
  ['C71.0', 'Neoplasia maligna do cérebro, exceto lobos e ventrículos'],
  ['C71.1', 'Neoplasia maligna do lobo frontal'],
  ['C71.2', 'Neoplasia maligna do lobo temporal'],
  ['C71.3', 'Neoplasia maligna do lobo parietal'],
  ['C71.4', 'Neoplasia maligna do lobo occipital'],
  ['C71.5', 'Neoplasia maligna do ventrículo cerebral'],
  ['C71.6', 'Neoplasia maligna do cerebelo'],
  ['C71.7', 'Neoplasia maligna do tronco encefálico'],
  ['C71.9', 'Neoplasia maligna do encéfalo, não especificada'],
  ['C72.0', 'Neoplasia maligna da medula espinhal'],
  ['C72.1', 'Neoplasia maligna da cauda equina'],
  ['C72.4', 'Neoplasia maligna do nervo acústico'],
  ['C72.5', 'Neoplasia maligna de outros nervos cranianos'],
  ['C79.3', 'Metástase cerebral'],
  ['C79.4', 'Neoplasia secundária de outras partes do SN'],
  ['D32.0', 'Neoplasia benigna das meninges cerebrais'],
  ['D32.9', 'Neoplasia benigna das meninges, não especificada'],
  ['D33.0', 'Neoplasia benigna do encéfalo, supratentorial'],
  ['D33.1', 'Neoplasia benigna do encéfalo, infratentorial'],
  ['D33.2', 'Neoplasia benigna do encéfalo, não especificada'],
  ['D33.3', 'Neoplasia benigna dos nervos cranianos'],
  ['D33.4', 'Neoplasia benigna da medula espinhal'],
  ['D35.2', 'Neoplasia benigna da hipófise'],
  ['D43.0', 'Neoplasia de comportamento incerto, encéfalo supratentorial'],
  ['D43.1', 'Neoplasia de comportamento incerto, encéfalo infratentorial'],
  ['D43.2', 'Neoplasia de comportamento incerto, encéfalo, não esp.'],

  // --- Endócrinas / metabólicas (relevantes em neuro) -----
  ['E03.9', 'Hipotireoidismo, não especificado'],
  ['E05.9', 'Hipertireoidismo, não especificado'],
  ['E10.4', 'Diabetes mellitus tipo 1 com complicações neurológicas'],
  ['E11.4', 'Diabetes mellitus tipo 2 com complicações neurológicas'],
  ['E51.2', 'Encefalopatia de Wernicke'],
  ['E53.8', 'Deficiência de outras vitaminas do complexo B'],
  ['E66.9', 'Obesidade, não especificada'],
  ['E78.5', 'Hiperlipidemia, não especificada'],
  ['E83.0', 'Distúrbios do metabolismo do cobre (Wilson)'],
  ['E84.9', 'Fibrose cística, não especificada'],
  ['E87.1', 'Hiposmolaridade e hiponatremia'],
  ['E87.2', 'Acidose'],

  // --- F00-F99 — Transtornos mentais -----------------------
  ['F00.0', 'Demência na doença de Alzheimer de início precoce'],
  ['F00.1', 'Demência na doença de Alzheimer de início tardio'],
  ['F00.2', 'Demência na doença de Alzheimer, forma atípica ou mista'],
  ['F00.9', 'Demência na doença de Alzheimer, não especificada'],
  ['F01.0', 'Demência vascular de início agudo'],
  ['F01.1', 'Demência por múltiplos infartos'],
  ['F01.2', 'Demência vascular subcortical'],
  ['F01.3', 'Demência vascular mista'],
  ['F01.9', 'Demência vascular, não especificada'],
  ['F02.0', 'Demência na doença de Pick'],
  ['F02.1', 'Demência na doença de Creutzfeldt-Jakob'],
  ['F02.2', 'Demência na doença de Huntington'],
  ['F02.3', 'Demência na doença de Parkinson'],
  ['F02.4', 'Demência na doença pelo HIV'],
  ['F02.8', 'Demência em outras doenças classificadas em outra parte'],
  ['F03',   'Demência não especificada'],
  ['F04',   'Síndrome amnésica orgânica não induzida por álcool'],
  ['F05.0', 'Delirium não superposto à demência'],
  ['F05.1', 'Delirium superposto à demência'],
  ['F05.9', 'Delirium não especificado'],
  ['F06.0', 'Alucinose orgânica'],
  ['F06.1', 'Estado catatônico orgânico'],
  ['F06.2', 'Transtorno delirante orgânico'],
  ['F06.3', 'Transtornos do humor orgânicos'],
  ['F06.4', 'Transtorno de ansiedade orgânico'],
  ['F06.5', 'Transtorno dissociativo orgânico'],
  ['F06.6', 'Transtorno de labilidade emocional orgânico'],
  ['F06.7', 'Transtorno cognitivo leve'],
  ['F06.9', 'Transtorno mental orgânico não especificado'],
  ['F07.0', 'Transtorno orgânico de personalidade'],
  ['F07.1', 'Síndrome pós-encefalítica'],
  ['F07.2', 'Síndrome pós-traumática'],
  ['F09',   'Transtorno mental orgânico ou sintomático não especificado'],
  ['F10.0', 'Transtornos por álcool — intoxicação aguda'],
  ['F10.1', 'Transtornos por álcool — uso nocivo'],
  ['F10.2', 'Transtornos por álcool — síndrome de dependência'],
  ['F10.3', 'Transtornos por álcool — síndrome de abstinência'],
  ['F10.4', 'Transtornos por álcool — abstinência com delirium'],
  ['F10.5', 'Transtornos por álcool — transtorno psicótico'],
  ['F10.6', 'Transtornos por álcool — síndrome amnésica'],
  ['F11.2', 'Dependência de opioides'],
  ['F12.2', 'Dependência de canabinoides'],
  ['F13.2', 'Dependência de sedativos ou hipnóticos'],
  ['F14.2', 'Dependência de cocaína'],
  ['F17.2', 'Dependência de tabaco'],
  ['F19.2', 'Dependência de múltiplas drogas'],
  ['F20.0', 'Esquizofrenia paranoide'],
  ['F20.9', 'Esquizofrenia, não especificada'],
  ['F22.0', 'Transtorno delirante'],
  ['F23.0', 'Transtorno psicótico agudo polimórfico'],
  ['F25.9', 'Transtorno esquizoafetivo, não especificado'],
  ['F31.0', 'Transtorno afetivo bipolar — episódio atual hipomaníaco'],
  ['F31.1', 'Transtorno afetivo bipolar — episódio atual maníaco'],
  ['F31.3', 'Transtorno afetivo bipolar — episódio atual depressivo leve/moderado'],
  ['F31.4', 'Transtorno afetivo bipolar — episódio depressivo grave sem psicose'],
  ['F31.5', 'Transtorno afetivo bipolar — episódio depressivo grave com psicose'],
  ['F31.9', 'Transtorno afetivo bipolar, não especificado'],
  ['F32.0', 'Episódio depressivo leve'],
  ['F32.1', 'Episódio depressivo moderado'],
  ['F32.2', 'Episódio depressivo grave sem sintomas psicóticos'],
  ['F32.3', 'Episódio depressivo grave com sintomas psicóticos'],
  ['F32.9', 'Episódio depressivo, não especificado'],
  ['F33.0', 'Transtorno depressivo recorrente — episódio leve'],
  ['F33.1', 'Transtorno depressivo recorrente — episódio moderado'],
  ['F33.2', 'Transtorno depressivo recorrente — episódio grave sem psicose'],
  ['F33.3', 'Transtorno depressivo recorrente — episódio grave com psicose'],
  ['F33.4', 'Transtorno depressivo recorrente, em remissão'],
  ['F33.9', 'Transtorno depressivo recorrente, não especificado'],
  ['F34.0', 'Ciclotimia'],
  ['F34.1', 'Distimia'],
  ['F40.0', 'Agorafobia'],
  ['F40.1', 'Fobia social'],
  ['F40.2', 'Fobias específicas'],
  ['F41.0', 'Transtorno de pânico'],
  ['F41.1', 'Ansiedade generalizada'],
  ['F41.2', 'Transtorno misto ansioso e depressivo'],
  ['F41.9', 'Transtorno ansioso, não especificado'],
  ['F42.0', 'Transtorno obsessivo-compulsivo — predomínio obsessões'],
  ['F42.1', 'Transtorno obsessivo-compulsivo — predomínio compulsões'],
  ['F42.9', 'TOC, não especificado'],
  ['F43.0', 'Reação aguda ao estresse'],
  ['F43.1', 'Estado de estresse pós-traumático (TEPT)'],
  ['F43.2', 'Transtornos de adaptação'],
  ['F44.4', 'Transtorno dissociativo motor'],
  ['F44.5', 'Convulsões dissociativas (pseudocrises)'],
  ['F44.7', 'Transtorno dissociativo misto'],
  ['F44.9', 'Transtorno dissociativo (de conversão), não especificado'],
  ['F45.0', 'Transtorno de somatização'],
  ['F45.1', 'Transtorno somatoforme indiferenciado'],
  ['F45.2', 'Transtorno hipocondríaco'],
  ['F45.4', 'Transtorno doloroso somatoforme persistente'],
  ['F48.0', 'Neurastenia'],
  ['F48.9', 'Transtorno neurótico, não especificado'],
  ['F50.0', 'Anorexia nervosa'],
  ['F50.2', 'Bulimia nervosa'],
  ['F51.0', 'Insônia não orgânica'],
  ['F51.1', 'Hipersonia não orgânica'],
  ['F51.2', 'Transtorno do ciclo sono-vigília não orgânico'],
  ['F51.3', 'Sonambulismo'],
  ['F51.5', 'Pesadelos'],
  ['F60.3', 'Transtorno de personalidade emocionalmente instável'],
  ['F70',   'Retardo mental leve'],
  ['F71',   'Retardo mental moderado'],
  ['F72',   'Retardo mental grave'],
  ['F79',   'Retardo mental não especificado'],
  ['F80.9', 'Transtorno do desenvolvimento da fala/linguagem, não esp.'],
  ['F84.0', 'Autismo infantil'],
  ['F84.5', 'Síndrome de Asperger'],
  ['F84.9', 'Transtorno global do desenvolvimento, não especificado'],
  ['F90.0', 'Distúrbio de atividade e atenção (TDAH)'],
  ['F90.9', 'TDAH, não especificado'],
  ['F95.2', 'Síndrome de Tourette'],
  ['F95.9', 'Tique, não especificado'],
  ['F98.0', 'Enurese não orgânica'],
  ['F99',   'Transtorno mental não especificado'],

  // --- G00-G99 — Sistema Nervoso (capítulo principal) -----
  ['G00.0', 'Meningite por Haemophilus'],
  ['G00.1', 'Meningite pneumocócica'],
  ['G00.2', 'Meningite estreptocócica'],
  ['G00.3', 'Meningite estafilocócica'],
  ['G00.8', 'Outras meningites bacterianas'],
  ['G00.9', 'Meningite bacteriana, não especificada'],
  ['G01',   'Meningite em doenças bacterianas classificadas em outra parte'],
  ['G02.0', 'Meningite em doenças virais classificadas em outra parte'],
  ['G02.1', 'Meningite em micoses'],
  ['G03.0', 'Meningite apiogênica'],
  ['G03.1', 'Meningite crônica'],
  ['G03.8', 'Meningite por outras causas especificadas'],
  ['G03.9', 'Meningite, não especificada'],
  ['G04.0', 'Encefalite aguda disseminada (ADEM)'],
  ['G04.1', 'Paraplegia espástica tropical'],
  ['G04.2', 'Meningoencefalite e meningomielite bacterianas'],
  ['G04.8', 'Outras encefalites, mielites e encefalomielites'],
  ['G04.9', 'Encefalite, mielite ou encefalomielite, não especificada'],
  ['G05.0', 'Encefalite/mielite em doenças bacterianas'],
  ['G05.1', 'Encefalite/mielite em doenças virais'],
  ['G05.8', 'Encefalite/mielite em outras doenças'],
  ['G06.0', 'Abscesso e granuloma intracraniano'],
  ['G06.1', 'Abscesso e granuloma intra-raquiano'],
  ['G06.2', 'Abscesso extradural e subdural, não especificado'],
  ['G07',   'Abscesso/granuloma intracraniano em doenças classif. em outra parte'],
  ['G08',   'Flebite e tromboflebite intracranianas/intra-raquianas'],
  ['G09',   'Sequelas de doenças inflamatórias do SNC'],
  ['G10',   'Doença de Huntington'],
  ['G11.0', 'Ataxia congênita não progressiva'],
  ['G11.1', 'Ataxia cerebelar de início precoce'],
  ['G11.2', 'Ataxia cerebelar de início tardio'],
  ['G11.3', 'Ataxia cerebelar com defeito da reparação do DNA'],
  ['G11.4', 'Paraplegia espástica hereditária'],
  ['G11.8', 'Outras ataxias hereditárias'],
  ['G11.9', 'Ataxia hereditária, não especificada'],
  ['G12.0', 'Atrofia muscular espinhal infantil tipo I (Werdnig-Hoffmann)'],
  ['G12.1', 'Outras atrofias musculares espinhais hereditárias'],
  ['G12.2', 'Doença do neurônio motor (ELA)'],
  ['G12.8', 'Outras atrofias musculares espinhais e síndromes correlatas'],
  ['G12.9', 'Atrofia muscular espinhal, não especificada'],
  ['G13.0', 'Neuromiopatia/neuropatia paraneoplásica'],
  ['G13.1', 'Atrofia sistêmica em outra doença com manifestação no SNC'],
  ['G14',   'Síndrome pós-pólio'],
  ['G20',   'Doença de Parkinson'],
  ['G21.0', 'Síndrome neuroléptica maligna'],
  ['G21.1', 'Parkinsonismo secundário induzido por outras drogas'],
  ['G21.2', 'Parkinsonismo secundário a outros agentes externos'],
  ['G21.3', 'Parkinsonismo pós-encefalítico'],
  ['G21.4', 'Parkinsonismo vascular'],
  ['G21.8', 'Outras formas de parkinsonismo secundário'],
  ['G21.9', 'Parkinsonismo secundário, não especificado'],
  ['G22',   'Parkinsonismo em doenças classificadas em outra parte'],
  ['G23.0', 'Doença de Hallervorden-Spatz'],
  ['G23.1', 'Oftalmoplegia supranuclear progressiva (Steele-Richardson-Olszewski)'],
  ['G23.2', 'Degeneração estriatonigral'],
  ['G23.8', 'Outras doenças degenerativas especificadas dos núcleos da base'],
  ['G23.9', 'Doença degenerativa dos núcleos da base, não especificada'],
  ['G24.0', 'Distonia induzida por drogas'],
  ['G24.1', 'Distonia idiopática familiar'],
  ['G24.2', 'Distonia idiopática não familiar'],
  ['G24.3', 'Torcicolo espasmódico'],
  ['G24.4', 'Distonia bucofacial idiopática'],
  ['G24.5', 'Blefaroespasmo'],
  ['G24.8', 'Outras distonias'],
  ['G24.9', 'Distonia, não especificada'],
  ['G25.0', 'Tremor essencial'],
  ['G25.1', 'Tremor induzido por drogas'],
  ['G25.2', 'Outras formas especificadas de tremor'],
  ['G25.3', 'Mioclonia'],
  ['G25.4', 'Coreia induzida por drogas'],
  ['G25.5', 'Outras coreias'],
  ['G25.6', 'Tiques induzidos por drogas e outros tiques de origem orgânica'],
  ['G25.8', 'Outras doenças extrapiramidais e distúrbios do movimento'],
  ['G25.9', 'Doença extrapiramidal e distúrbio do movimento, não esp.'],
  ['G26',   'Doenças extrapiramidais em doenças classificadas em outra parte'],
  ['G30.0', 'Doença de Alzheimer de início precoce'],
  ['G30.1', 'Doença de Alzheimer de início tardio'],
  ['G30.8', 'Outras formas de doença de Alzheimer'],
  ['G30.9', 'Doença de Alzheimer, não especificada'],
  ['G31.0', 'Atrofia cerebral circunscrita'],
  ['G31.1', 'Degeneração cerebral senil'],
  ['G31.2', 'Degeneração do SN devida ao álcool'],
  ['G31.8', 'Outras doenças degenerativas especificadas do SN'],
  ['G31.9', 'Doença degenerativa do SN, não especificada'],
  ['G32.0', 'Degeneração combinada subaguda da medula espinhal'],
  ['G32.8', 'Outros transtornos degenerativos especificados do SN'],
  ['G35',   'Esclerose múltipla'],
  ['G36.0', 'Neuromielite óptica (doença de Devic)'],
  ['G36.1', 'Leucoencefalite hemorrágica aguda e subaguda'],
  ['G36.8', 'Outras desmielinizações disseminadas agudas especificadas'],
  ['G36.9', 'Desmielinização disseminada aguda, não especificada'],
  ['G37.0', 'Esclerose difusa'],
  ['G37.1', 'Desmielinização central do corpo caloso'],
  ['G37.2', 'Mielinólise pontina central'],
  ['G37.3', 'Mielite transversa aguda na doença desmielinizante'],
  ['G37.5', 'Esclerose concêntrica (Baló)'],
  ['G37.8', 'Outras doenças desmielinizantes especificadas do SNC'],
  ['G37.9', 'Doença desmielinizante do SNC, não especificada'],
  ['G40.0', 'Epilepsia/síndromes epilépticas idiopáticas focais com crises focais'],
  ['G40.1', 'Epilepsia/síndromes epilépticas sintomáticas focais com crises focais simples'],
  ['G40.2', 'Epilepsia/síndromes epilépticas sintomáticas focais com crises focais complexas'],
  ['G40.3', 'Epilepsia/síndromes epilépticas generalizadas idiopáticas'],
  ['G40.4', 'Outras epilepsias/síndromes epilépticas generalizadas'],
  ['G40.5', 'Síndromes epilépticas especiais'],
  ['G40.6', 'Crises de grande mal, não especificadas (com/sem pequeno mal)'],
  ['G40.7', 'Pequeno mal, não especificado, sem crises de grande mal'],
  ['G40.8', 'Outras epilepsias'],
  ['G40.9', 'Epilepsia, não especificada'],
  ['G41.0', 'Estado de mal de grande mal'],
  ['G41.1', 'Estado de mal de pequeno mal'],
  ['G41.2', 'Estado de mal epiléptico parcial complexo'],
  ['G41.8', 'Outros estados de mal epilépticos'],
  ['G41.9', 'Estado de mal epiléptico, não especificado'],
  ['G43.0', 'Enxaqueca sem aura (enxaqueca comum)'],
  ['G43.1', 'Enxaqueca com aura (enxaqueca clássica)'],
  ['G43.2', 'Estado de mal enxaquecoso'],
  ['G43.3', 'Enxaqueca complicada'],
  ['G43.8', 'Outras enxaquecas'],
  ['G43.9', 'Enxaqueca, não especificada'],
  ['G44.0', 'Síndrome da cefaleia em salvas'],
  ['G44.1', 'Cefaleia vascular não classificada em outra parte'],
  ['G44.2', 'Cefaleia tensional'],
  ['G44.3', 'Cefaleia crônica pós-traumática'],
  ['G44.4', 'Cefaleia induzida por uso de medicamentos'],
  ['G44.8', 'Outras síndromes de cefaleia especificadas'],
  ['G45.0', 'Síndrome arterial vértebro-basilar'],
  ['G45.1', 'Síndrome da artéria carótida (hemisférica)'],
  ['G45.2', 'Síndromes arteriais cerebrais bilaterais e múltiplas'],
  ['G45.3', 'Amaurose fugaz'],
  ['G45.4', 'Amnésia global transitória'],
  ['G45.8', 'Outros AITs e síndromes correlatas'],
  ['G45.9', 'Acidente isquêmico transitório (AIT), não especificado'],
  ['G46.0', 'Síndrome da artéria cerebral média'],
  ['G46.1', 'Síndrome da artéria cerebral anterior'],
  ['G46.2', 'Síndrome da artéria cerebral posterior'],
  ['G46.3', 'Síndromes cerebrais do tronco encefálico'],
  ['G46.4', 'Síndrome cerebelar em doenças cerebrovasculares'],
  ['G46.5', 'Síndrome lacunar motora pura'],
  ['G46.6', 'Síndrome lacunar sensorial pura'],
  ['G46.7', 'Outras síndromes lacunares'],
  ['G46.8', 'Outras síndromes vasculares cerebrais'],
  ['G47.0', 'Distúrbios do início e da manutenção do sono (insônias)'],
  ['G47.1', 'Distúrbios da sonolência excessiva (hipersonias)'],
  ['G47.2', 'Distúrbios do ciclo sono-vigília'],
  ['G47.3', 'Apneia do sono'],
  ['G47.4', 'Narcolepsia e cataplexia'],
  ['G47.8', 'Outros distúrbios do sono'],
  ['G47.9', 'Distúrbio do sono, não especificado'],
  ['G50.0', 'Neuralgia do trigêmeo'],
  ['G50.1', 'Dor facial atípica'],
  ['G50.8', 'Outros transtornos do nervo trigêmeo'],
  ['G50.9', 'Transtorno do nervo trigêmeo, não especificado'],
  ['G51.0', 'Paralisia de Bell'],
  ['G51.1', 'Ganglionite geniculada'],
  ['G51.2', 'Síndrome de Melkersson-Rosenthal'],
  ['G51.3', 'Espasmo hemifacial clônico'],
  ['G51.4', 'Mioquimia facial'],
  ['G51.8', 'Outros transtornos do nervo facial'],
  ['G51.9', 'Transtorno do nervo facial, não especificado'],
  ['G52.0', 'Transtornos do nervo olfatório'],
  ['G52.1', 'Transtornos do nervo glossofaríngeo'],
  ['G52.2', 'Transtornos do nervo vago'],
  ['G52.3', 'Transtornos do nervo hipoglosso'],
  ['G52.7', 'Transtornos múltiplos de nervos cranianos'],
  ['G52.8', 'Transtornos de outros nervos cranianos especificados'],
  ['G52.9', 'Transtorno de nervo craniano, não especificado'],
  ['G53.0', 'Neuralgia pós-herpética'],
  ['G53.1', 'Paralisias múltiplas dos nervos cranianos em doenças infecciosas'],
  ['G54.0', 'Transtornos do plexo braquial'],
  ['G54.1', 'Transtornos do plexo lombossacral'],
  ['G54.2', 'Transtornos das raízes cervicais NCOP'],
  ['G54.3', 'Transtornos das raízes torácicas NCOP'],
  ['G54.4', 'Transtornos das raízes lombossacrais NCOP'],
  ['G54.5', 'Amiotrofia neurálgica'],
  ['G54.6', 'Síndrome do membro fantasma com dor'],
  ['G54.7', 'Síndrome do membro fantasma sem dor'],
  ['G54.8', 'Outros transtornos das raízes e plexos nervosos'],
  ['G54.9', 'Transtorno de raiz/plexo nervoso, não especificado'],
  ['G55.0', 'Compressões de raízes/plexos em neoplasias'],
  ['G55.1', 'Compressões de raízes/plexos em transtornos dos discos intervertebrais'],
  ['G55.2', 'Compressões de raízes/plexos em espondilose'],
  ['G55.3', 'Compressões de raízes/plexos em outras dorsopatias'],
  ['G55.8', 'Compressões de raízes/plexos em outras doenças'],
  ['G56.0', 'Síndrome do túnel do carpo'],
  ['G56.1', 'Outras lesões do nervo mediano'],
  ['G56.2', 'Lesão do nervo cubital (ulnar)'],
  ['G56.3', 'Lesão do nervo radial'],
  ['G56.4', 'Causalgia'],
  ['G56.8', 'Outras mononeuropatias do membro superior'],
  ['G56.9', 'Mononeuropatia do membro superior, não especificada'],
  ['G57.0', 'Lesão do nervo ciático'],
  ['G57.1', 'Meralgia parestésica'],
  ['G57.2', 'Lesão do nervo crural (femoral)'],
  ['G57.3', 'Lesão do nervo poplíteo lateral (fibular)'],
  ['G57.4', 'Lesão do nervo poplíteo medial (tibial)'],
  ['G57.5', 'Síndrome do túnel do tarso'],
  ['G57.6', 'Lesão do nervo plantar'],
  ['G57.8', 'Outras mononeuralgias do membro inferior'],
  ['G57.9', 'Mononeuropatia do membro inferior, não especificada'],
  ['G58.0', 'Neuropatia intercostal'],
  ['G58.7', 'Mononeurite múltipla'],
  ['G58.8', 'Outras mononeuropatias especificadas'],
  ['G58.9', 'Mononeuropatia, não especificada'],
  ['G60.0', 'Neuropatia hereditária motora e sensorial (Charcot-Marie-Tooth)'],
  ['G60.1', 'Doença de Refsum'],
  ['G60.2', 'Neuropatia associada a ataxia hereditária'],
  ['G60.3', 'Neuropatia progressiva idiopática'],
  ['G60.8', 'Outras neuropatias hereditárias e idiopáticas'],
  ['G60.9', 'Neuropatia hereditária e idiopática, não especificada'],
  ['G61.0', 'Síndrome de Guillain-Barré'],
  ['G61.1', 'Neuropatia sérica'],
  ['G61.8', 'Outras polineuropatias inflamatórias'],
  ['G61.9', 'Polineuropatia inflamatória, não especificada'],
  ['G62.0', 'Polineuropatia induzida por drogas'],
  ['G62.1', 'Polineuropatia alcoólica'],
  ['G62.2', 'Polineuropatia devida a outros agentes tóxicos'],
  ['G62.8', 'Outras polineuropatias especificadas'],
  ['G62.9', 'Polineuropatia, não especificada'],
  ['G63.0', 'Polineuropatia em doenças infecciosas e parasitárias'],
  ['G63.1', 'Polineuropatia em doenças neoplásicas'],
  ['G63.2', 'Polineuropatia diabética'],
  ['G63.3', 'Polineuropatia em outras doenças endócrinas e metabólicas'],
  ['G63.5', 'Polineuropatia em doenças do tecido conjuntivo sistêmicas'],
  ['G63.6', 'Polineuropatia em outros transtornos osteomusculares'],
  ['G63.8', 'Polineuropatia em outras doenças classificadas em outra parte'],
  ['G64',   'Outros transtornos do SN periférico'],
  ['G70.0', 'Miastenia gravis'],
  ['G70.1', 'Transtornos tóxico-mioneurais'],
  ['G70.2', 'Miastenia congênita ou do desenvolvimento'],
  ['G70.8', 'Outros transtornos miastênicos especificados'],
  ['G70.9', 'Transtorno mioneural, não especificado'],
  ['G71.0', 'Distrofia muscular'],
  ['G71.1', 'Transtornos miotônicos'],
  ['G71.2', 'Miopatias congênitas'],
  ['G71.3', 'Miopatia mitocondrial NCOP'],
  ['G71.8', 'Outros transtornos primários de músculos'],
  ['G71.9', 'Transtorno muscular primário, não especificado'],
  ['G72.0', 'Miopatia induzida por drogas'],
  ['G72.1', 'Miopatia alcoólica'],
  ['G72.2', 'Miopatia devida a outros agentes tóxicos'],
  ['G72.3', 'Paralisia periódica'],
  ['G72.4', 'Miopatia inflamatória NCOP'],
  ['G72.8', 'Outras miopatias especificadas'],
  ['G72.9', 'Miopatia, não especificada'],
  ['G73.0', 'Síndromes miastênicas em doenças endócrinas'],
  ['G73.1', 'Síndrome de Eaton-Lambert'],
  ['G80.0', 'Paralisia cerebral espástica quadriplégica'],
  ['G80.1', 'Paralisia cerebral espástica diplégica'],
  ['G80.2', 'Paralisia cerebral espástica hemiplégica'],
  ['G80.3', 'Paralisia cerebral discinética'],
  ['G80.4', 'Paralisia cerebral atáxica'],
  ['G80.8', 'Outros tipos de paralisia cerebral'],
  ['G80.9', 'Paralisia cerebral, não especificada'],
  ['G81.0', 'Hemiplegia flácida'],
  ['G81.1', 'Hemiplegia espástica'],
  ['G81.9', 'Hemiplegia, não especificada'],
  ['G82.0', 'Paraplegia flácida'],
  ['G82.1', 'Paraplegia espástica'],
  ['G82.2', 'Paraplegia, não especificada'],
  ['G82.3', 'Tetraplegia flácida'],
  ['G82.4', 'Tetraplegia espástica'],
  ['G82.5', 'Tetraplegia, não especificada'],
  ['G83.0', 'Diplegia dos membros superiores'],
  ['G83.1', 'Monoplegia do membro inferior'],
  ['G83.2', 'Monoplegia do membro superior'],
  ['G83.3', 'Monoplegia, não especificada'],
  ['G83.4', 'Síndrome da cauda equina'],
  ['G83.8', 'Outras síndromes paralíticas especificadas'],
  ['G83.9', 'Síndrome paralítica, não especificada'],
  ['G90.0', 'Neuropatia idiopática autônoma periférica'],
  ['G90.3', 'Atrofia de múltiplos sistemas (Shy-Drager)'],
  ['G90.8', 'Outros transtornos do SN autônomo'],
  ['G90.9', 'Transtorno do SN autônomo, não especificado'],
  ['G91.0', 'Hidrocefalia comunicante'],
  ['G91.1', 'Hidrocefalia obstrutiva'],
  ['G91.2', 'Hidrocefalia de pressão normal'],
  ['G91.3', 'Hidrocefalia pós-traumática, não especificada'],
  ['G91.8', 'Outras hidrocefalias'],
  ['G91.9', 'Hidrocefalia, não especificada'],
  ['G92',   'Encefalopatia tóxica'],
  ['G93.0', 'Cistos cerebrais'],
  ['G93.1', 'Lesão encefálica anóxica NCOP'],
  ['G93.2', 'Hipertensão intracraniana benigna'],
  ['G93.3', 'Síndrome da fadiga pós-viral'],
  ['G93.4', 'Encefalopatia, não especificada'],
  ['G93.5', 'Compressão do encéfalo'],
  ['G93.6', 'Edema cerebral'],
  ['G93.7', 'Síndrome de Reye'],
  ['G93.8', 'Outros transtornos especificados do encéfalo'],
  ['G93.9', 'Transtorno do encéfalo, não especificado'],
  ['G95.0', 'Siringomielia e siringobulbia'],
  ['G95.1', 'Mielopatias vasculares'],
  ['G95.2', 'Compressão da medula espinhal, não especificada'],
  ['G95.8', 'Outras doenças especificadas da medula espinhal'],
  ['G95.9', 'Doença da medula espinhal, não especificada'],
  ['G96.0', 'Fístula liquórica'],
  ['G96.1', 'Transtornos das meninges NCOP'],
  ['G96.8', 'Outros transtornos especificados do SNC'],
  ['G96.9', 'Transtorno do SNC, não especificado'],
  ['G97.0', 'Fístula liquórica por punção espinhal'],
  ['G97.1', 'Outra reação a punção espinhal/lombar'],
  ['G97.2', 'Hipotensão intracraniana após derivação ventricular'],
  ['G97.8', 'Outros transtornos pós-procedimento do SN'],
  ['G98',   'Outros transtornos do SN NCOP'],
  ['G99.0', 'Neuropatia autônoma em doenças endócrinas e metabólicas'],
  ['G99.1', 'Outros transtornos do SN autônomo em doenças classif. em outra parte'],
  ['G99.2', 'Mielopatia em doenças classificadas em outra parte'],
  ['G99.8', 'Outros transtornos especificados do SN em doenças classif. em outra parte'],

  // --- H — neuro-oftalmologia / neuro-otologia -----------
  ['H46',   'Neurite óptica'],
  ['H47.0', 'Afecções do nervo óptico NCOP'],
  ['H47.1', 'Edema da papila, não especificado'],
  ['H47.2', 'Atrofia óptica'],
  ['H47.5', 'Afecções de outras vias ópticas'],
  ['H47.6', 'Afecções do córtex visual'],
  ['H49.0', 'Paralisia do III nervo (oculomotor)'],
  ['H49.1', 'Paralisia do IV nervo (troclear)'],
  ['H49.2', 'Paralisia do VI nervo (abducente)'],
  ['H49.3', 'Oftalmoplegia total externa'],
  ['H50.0', 'Estrabismo concomitante convergente'],
  ['H51.0', 'Paralisia do olhar conjugado'],
  ['H53.0', 'Ambliopia ex anopsia'],
  ['H53.1', 'Distúrbios visuais subjetivos'],
  ['H53.2', 'Diplopia'],
  ['H53.4', 'Defeitos do campo visual'],
  ['H55',   'Nistagmo e outros movimentos oculares irregulares'],
  ['H81.0', 'Doença de Ménière'],
  ['H81.1', 'Vertigem paroxística posicional benigna (VPPB)'],
  ['H81.2', 'Neuronite vestibular'],
  ['H81.3', 'Outras vertigens periféricas'],
  ['H81.4', 'Vertigem de origem central'],
  ['H81.9', 'Transtorno da função vestibular, não especificado'],
  ['H93.1', 'Zumbido (subjetivo)'],

  // --- I — Cerebrovasculares e correlatos ----------------
  ['I10',   'Hipertensão essencial (primária)'],
  ['I11.9', 'Doença cardíaca hipertensiva sem insuficiência cardíaca'],
  ['I15.9', 'Hipertensão secundária, não especificada'],
  ['I20.9', 'Angina pectoris, não especificada'],
  ['I21.9', 'Infarto agudo do miocárdio, não especificado'],
  ['I25.9', 'Doença isquêmica crônica do coração, não especificada'],
  ['I47.1', 'Taquicardia supraventricular'],
  ['I48.0', 'Fibrilação atrial paroxística'],
  ['I48.2', 'Fibrilação atrial crônica'],
  ['I48.9', 'Fibrilação e flutter atrial, não especificado'],
  ['I50.9', 'Insuficiência cardíaca, não especificada'],
  ['I60.0', 'HSA de sifão e bifurcação carotídea'],
  ['I60.1', 'HSA de artéria cerebral média'],
  ['I60.2', 'HSA de artéria comunicante anterior'],
  ['I60.3', 'HSA de artéria comunicante posterior'],
  ['I60.4', 'HSA de artéria basilar'],
  ['I60.5', 'HSA de artéria vertebral'],
  ['I60.6', 'HSA de outras artérias intracranianas'],
  ['I60.7', 'HSA de artéria intracraniana, não especificada'],
  ['I60.8', 'Outras hemorragias subaracnóideas'],
  ['I60.9', 'HSA, não especificada'],
  ['I61.0', 'Hemorragia intracerebral hemisférica subcortical'],
  ['I61.1', 'Hemorragia intracerebral hemisférica cortical'],
  ['I61.2', 'Hemorragia intracerebral hemisférica, não especificada'],
  ['I61.3', 'Hemorragia intracerebral do tronco encefálico'],
  ['I61.4', 'Hemorragia intracerebral cerebelar'],
  ['I61.5', 'Hemorragia intracerebral intraventricular'],
  ['I61.6', 'Hemorragia intracerebral de localizações múltiplas'],
  ['I61.8', 'Outras hemorragias intracerebrais'],
  ['I61.9', 'Hemorragia intracerebral, não especificada'],
  ['I62.0', 'Hemorragia subdural (aguda) (não traumática)'],
  ['I62.1', 'Hemorragia extradural não traumática'],
  ['I62.9', 'Hemorragia intracraniana (não traumática), não especificada'],
  ['I63.0', 'Infarto cerebral devido a trombose das artérias pré-cerebrais'],
  ['I63.1', 'Infarto cerebral devido a embolia das artérias pré-cerebrais'],
  ['I63.2', 'Infarto cerebral devido a oclusão/estenose pré-cerebrais não especif.'],
  ['I63.3', 'Infarto cerebral devido a trombose de artérias cerebrais'],
  ['I63.4', 'Infarto cerebral devido a embolia de artérias cerebrais'],
  ['I63.5', 'Infarto cerebral devido a oclusão/estenose cerebrais não especif.'],
  ['I63.6', 'Infarto cerebral devido a trombose venosa cerebral, não piogênica'],
  ['I63.8', 'Outros infartos cerebrais'],
  ['I63.9', 'Infarto cerebral, não especificado'],
  ['I64',   'AVC não especificado como hemorrágico ou isquêmico'],
  ['I65.0', 'Oclusão e estenose da artéria vertebral'],
  ['I65.1', 'Oclusão e estenose da artéria basilar'],
  ['I65.2', 'Oclusão e estenose da artéria carótida'],
  ['I65.3', 'Oclusão e estenose de artérias pré-cerebrais múltiplas e bilaterais'],
  ['I65.8', 'Oclusão e estenose de outras artérias pré-cerebrais'],
  ['I65.9', 'Oclusão e estenose de artéria pré-cerebral não especificada'],
  ['I66.0', 'Oclusão e estenose da artéria cerebral média'],
  ['I66.1', 'Oclusão e estenose da artéria cerebral anterior'],
  ['I66.2', 'Oclusão e estenose da artéria cerebral posterior'],
  ['I66.3', 'Oclusão e estenose das artérias cerebelares'],
  ['I66.4', 'Oclusão e estenose de múltiplas artérias cerebrais e bilaterais'],
  ['I66.8', 'Oclusão e estenose de outra artéria cerebral'],
  ['I66.9', 'Oclusão e estenose de artéria cerebral não especificada'],
  ['I67.0', 'Dissecção das artérias cerebrais sem ruptura'],
  ['I67.1', 'Aneurisma cerebral, sem ruptura'],
  ['I67.2', 'Aterosclerose cerebral'],
  ['I67.3', 'Leucoencefalopatia vascular progressiva (Binswanger)'],
  ['I67.4', 'Encefalopatia hipertensiva'],
  ['I67.5', 'Doença de Moyamoya'],
  ['I67.6', 'Trombose não piogênica do sistema venoso intracraniano'],
  ['I67.7', 'Arterite cerebral NCOP'],
  ['I67.8', 'Outras doenças cerebrovasculares especificadas'],
  ['I67.9', 'Doença cerebrovascular, não especificada'],
  ['I68.0', 'Angiopatia amiloide cerebral'],
  ['I68.1', 'Arterite cerebral em doenças classificadas em outra parte'],
  ['I68.2', 'Arteriopatia cerebral em outras doenças'],
  ['I68.8', 'Outros transtornos cerebrovasculares em doenças classif. em outra parte'],
  ['I69.0', 'Sequelas de hemorragia subaracnóidea'],
  ['I69.1', 'Sequelas de hemorragia intracerebral'],
  ['I69.2', 'Sequelas de outras hemorragias intracranianas não traumáticas'],
  ['I69.3', 'Sequelas de infarto cerebral'],
  ['I69.4', 'Sequelas de AVC, não esp. como hemorrágico ou isquêmico'],
  ['I69.8', 'Sequelas de outras doenças cerebrovasculares e das não especificadas'],
  ['I73.9', 'Doença vascular periférica, não especificada'],
  ['I82.9', 'Embolia e trombose venosas, não especificadas'],

  // --- M — Dores, coluna, musculoesquelético relevante ---
  ['M25.5', 'Dor articular'],
  ['M40.0', 'Cifose postural'],
  ['M41.9', 'Escoliose, não especificada'],
  ['M42.1', 'Osteocondrose espinhal do adulto'],
  ['M43.6', 'Torcicolo'],
  ['M47.0', 'Síndromes de compressão da artéria espinhal/anterior'],
  ['M47.1', 'Outras espondiloses com mielopatia'],
  ['M47.2', 'Outras espondiloses com radiculopatia'],
  ['M47.8', 'Outras espondiloses'],
  ['M47.9', 'Espondilose, não especificada'],
  ['M48.0', 'Estenose espinhal'],
  ['M50.0', 'Transtorno de disco cervical com mielopatia'],
  ['M50.1', 'Transtorno de disco cervical com radiculopatia'],
  ['M50.2', 'Outros deslocamentos de disco cervical'],
  ['M50.3', 'Outras degenerações de disco cervical'],
  ['M50.9', 'Transtorno de disco cervical, não especificado'],
  ['M51.0', 'Transtorno de disco lombar com mielopatia'],
  ['M51.1', 'Transtorno de disco lombar e outros com radiculopatia'],
  ['M51.2', 'Outros deslocamentos de disco intervertebral especificados'],
  ['M51.3', 'Outras degenerações de disco intervertebral especificadas'],
  ['M51.9', 'Transtorno de disco intervertebral, não especificado'],
  ['M53.0', 'Síndrome cervicocraniana'],
  ['M53.1', 'Síndrome cervicobraquial'],
  ['M54.0', 'Paniculite atingindo regiões do pescoço/dorso'],
  ['M54.1', 'Radiculopatia'],
  ['M54.2', 'Cervicalgia'],
  ['M54.3', 'Ciática'],
  ['M54.4', 'Lumbago com ciática'],
  ['M54.5', 'Lombalgia'],
  ['M54.6', 'Dor na coluna torácica'],
  ['M54.8', 'Outras dorsalgias'],
  ['M54.9', 'Dorsalgia, não especificada'],
  ['M62.6', 'Distensão muscular'],
  ['M79.0', 'Reumatismo, não especificado'],
  ['M79.1', 'Mialgia'],
  ['M79.2', 'Neuralgia/neurite, não especificadas'],
  ['M79.7', 'Fibromialgia'],
  ['M89.9', 'Transtorno ósseo, não especificado'],

  // --- N — bexiga neurogênica e correlatos ---------------
  ['N31.0', 'Bexiga neuropática não inibida NCOP'],
  ['N31.1', 'Bexiga neuropática reflexa NCOP'],
  ['N31.2', 'Bexiga neuropática flácida NCOP'],
  ['N31.9', 'Disfunção neuromuscular da bexiga, não especificada'],
  ['N39.4', 'Outras incontinências urinárias especificadas'],

  // --- Q — malformações congênitas SN --------------------
  ['Q00.0', 'Anencefalia'],
  ['Q01.9', 'Encefalocele, não especificada'],
  ['Q03.9', 'Hidrocefalia congênita, não especificada'],
  ['Q04.0', 'Malformações congênitas do corpo caloso'],
  ['Q04.3', 'Outras anomalias por redução do encéfalo'],
  ['Q04.6', 'Cistos cerebrais congênitos'],
  ['Q04.9', 'Malformação congênita do encéfalo, não especificada'],
  ['Q05.9', 'Espinha bífida, não especificada'],
  ['Q06.9', 'Malformação congênita da medula espinhal, não especificada'],
  ['Q07.0', 'Síndrome de Arnold-Chiari'],
  ['Q07.9', 'Malformação congênita do SN, não especificada'],
  ['Q85.0', 'Neurofibromatose (não maligna)'],
  ['Q85.1', 'Esclerose tuberosa'],
  ['Q87.0', 'Síndromes que afetam a aparência facial'],

  // --- R — Sintomas e sinais ----------------------------
  ['R00.0', 'Taquicardia, não especificada'],
  ['R00.1', 'Bradicardia, não especificada'],
  ['R03.0', 'Leitura aumentada da pressão arterial sem diagnóstico de HAS'],
  ['R06.8', 'Outras anormalidades especificadas da respiração'],
  ['R07.4', 'Dor torácica, não especificada'],
  ['R10.4', 'Dor abdominal'],
  ['R11',   'Náusea e vômitos'],
  ['R20.0', 'Anestesia da pele'],
  ['R20.1', 'Hipoestesia da pele'],
  ['R20.2', 'Parestesia da pele'],
  ['R20.3', 'Hiperestesia'],
  ['R20.8', 'Outras alterações da sensibilidade cutânea'],
  ['R25.0', 'Movimentos anormais da cabeça'],
  ['R25.1', 'Tremor não especificado'],
  ['R25.2', 'Cãibra e espasmo'],
  ['R25.3', 'Fasciculação'],
  ['R25.8', 'Outros movimentos involuntários anormais'],
  ['R26.0', 'Marcha atáxica'],
  ['R26.1', 'Marcha paralítica'],
  ['R26.2', 'Dificuldade para andar NCOP'],
  ['R26.3', 'Imobilidade'],
  ['R26.8', 'Outras alterações da marcha e da mobilidade'],
  ['R27.0', 'Ataxia, não especificada'],
  ['R27.8', 'Outras incoordenações'],
  ['R29.0', 'Tetania'],
  ['R29.1', 'Meningismo'],
  ['R29.2', 'Reflexos anormais'],
  ['R29.3', 'Postura anormal'],
  ['R29.4', 'Quadril estalando'],
  ['R29.5', 'Imobilidade transitória'],
  ['R29.6', 'Quedas, não classificadas em outra parte'],
  ['R29.8', 'Outros sintomas relacionados ao SN/sistema osteomuscular'],
  ['R32',   'Incontinência urinária não especificada'],
  ['R39.1', 'Outras dificuldades para a micção'],
  ['R40.0', 'Sonolência'],
  ['R40.1', 'Estupor'],
  ['R40.2', 'Coma, não especificado'],
  ['R41.0', 'Desorientação, não especificada'],
  ['R41.1', 'Amnésia anterógrada'],
  ['R41.2', 'Amnésia retrógrada'],
  ['R41.3', 'Outras amnésias'],
  ['R41.8', 'Outros sintomas/sinais relativos a funções cognitivas/consciência'],
  ['R42',   'Tontura e instabilidade'],
  ['R44.0', 'Alucinações auditivas'],
  ['R44.1', 'Alucinações visuais'],
  ['R44.3', 'Alucinações, não especificadas'],
  ['R45.0', 'Nervosismo'],
  ['R45.1', 'Inquietação e agitação'],
  ['R45.2', 'Infelicidade'],
  ['R45.4', 'Irritabilidade e cólera'],
  ['R47.0', 'Disfasia e afasia'],
  ['R47.1', 'Disartria e anartria'],
  ['R47.8', 'Outras alterações da fala e as não especificadas'],
  ['R48.0', 'Dislexia e alexia'],
  ['R48.1', 'Agnosia'],
  ['R48.2', 'Apraxia'],
  ['R48.8', 'Outros transtornos simbólicos NCOP'],
  ['R49.0', 'Disfonia'],
  ['R51',   'Cefaleia'],
  ['R52.0', 'Dor aguda'],
  ['R52.1', 'Dor crônica intratável'],
  ['R52.2', 'Outras dores crônicas'],
  ['R53',   'Mal-estar e fadiga'],
  ['R54',   'Senilidade'],
  ['R55',   'Síncope e colapso'],
  ['R56.0', 'Convulsões febris'],
  ['R56.8', 'Outras convulsões e as não especificadas'],
  ['R56.9', 'Convulsões, não especificadas'],
  ['R63.0', 'Anorexia'],
  ['R63.4', 'Perda de peso anormal'],

  // --- S — Trauma SN -------------------------------------
  ['S00.0', 'Trauma superficial do couro cabeludo'],
  ['S01.0', 'Ferimento do couro cabeludo'],
  ['S02.0', 'Fratura da abóbada do crânio'],
  ['S02.1', 'Fratura da base do crânio'],
  ['S02.7', 'Fraturas múltiplas envolvendo o crânio e os ossos da face'],
  ['S02.9', 'Fratura do crânio e dos ossos da face, parte não especificada'],
  ['S04.0', 'Traumatismo dos nervos e vias ópticas'],
  ['S04.3', 'Traumatismo do nervo trigêmeo'],
  ['S04.5', 'Traumatismo do nervo facial'],
  ['S04.7', 'Traumatismo do nervo acessório'],
  ['S06.0', 'Concussão cerebral'],
  ['S06.1', 'Edema cerebral traumático'],
  ['S06.2', 'Traumatismo cerebral difuso'],
  ['S06.3', 'Traumatismo cerebral focal'],
  ['S06.4', 'Hemorragia epidural traumática'],
  ['S06.5', 'Hemorragia subdural traumática'],
  ['S06.6', 'Hemorragia subaracnóidea traumática'],
  ['S06.7', 'Traumatismo intracraniano com coma prolongado'],
  ['S06.8', 'Outros traumatismos intracranianos'],
  ['S06.9', 'Traumatismo intracraniano, não especificado'],
  ['S07',   'Lesão por esmagamento da cabeça'],
  ['S09.7', 'Traumatismos múltiplos da cabeça'],
  ['S09.9', 'Traumatismo da cabeça, não especificado'],
  ['S12.9', 'Fratura cervical não especificada'],
  ['S13.4', 'Entorse e distensão da coluna cervical'],
  ['S14.0', 'Concussão e edema da medula cervical'],
  ['S14.1', 'Outras lesões e as não especificadas da medula cervical'],
  ['S22.0', 'Fratura de vértebra torácica'],
  ['S24.1', 'Outras lesões e as não especificadas da medula dorsal'],
  ['S32.0', 'Fratura de vértebra lombar'],
  ['S34.1', 'Outras lesões da medula lombar'],

  // --- T — efeitos drogas, lesões correlatas -------------
  ['T36.7', 'Intoxicação por antimicóticos'],
  ['T42.3', 'Intoxicação por barbitúricos'],
  ['T42.4', 'Intoxicação por benzodiazepínicos'],
  ['T42.5', 'Intoxicação por antiepilépticos NCOP'],
  ['T42.7', 'Intoxicação por antiepilépticos/sedativos NE'],
  ['T43.0', 'Intoxicação por antidepressivos tricíclicos'],
  ['T43.2', 'Intoxicação por outros antidepressivos NCOP'],
  ['T43.3', 'Intoxicação por antipsicóticos'],
  ['T46.5', 'Intoxicação por outras drogas anti-hipertensivas'],
  ['T78.4', 'Alergia, não especificada'],
  ['T79.5', 'Anúria traumática'],
  ['T81.4', 'Infecção pós-procedimento NCOP'],
  ['T88.6', 'Choque anafilático devido a efeito adverso de droga'],

  // --- Z — observação, fatores de risco, exposições ------
  ['Z00.0', 'Exame médico geral'],
  ['Z03.3', 'Observação por suspeita de transtornos do SN'],
  ['Z03.6', 'Observação por suspeita de efeitos tóxicos de substância ingerida'],
  ['Z08.0', 'Exame de seguimento após cirurgia por neoplasia'],
  ['Z09.0', 'Exame de seguimento após cirurgia por outras condições'],
  ['Z13.4', 'Rastreamento de transtornos mentais e comportamentais infância'],
  ['Z51.0', 'Sessão de radioterapia'],
  ['Z51.1', 'Sessão de quimioterapia por neoplasia'],
  ['Z71.4', 'Aconselhamento e supervisão sobre uso de álcool'],
  ['Z71.5', 'Aconselhamento e supervisão sobre uso de drogas'],
  ['Z72.0', 'Uso de tabaco'],
  ['Z73.0', 'Burnout'],
  ['Z73.3', 'Estresse, não classificado em outra parte'],
  ['Z76.5', 'Pessoa simulando doença (simulação consciente)'],
  ['Z80.4', 'História familiar de neoplasia maligna do SN'],
  ['Z81.8', 'História familiar de outros transtornos mentais'],
  ['Z82.3', 'História familiar de AVC'],
  ['Z82.7', 'História familiar de malformações/doenças hereditárias do SN'],
  ['Z86.4', 'História pessoal de abuso de substâncias psicoativas'],
  ['Z86.7', 'História pessoal de doenças do aparelho circulatório'],
  ['Z87.8', 'História pessoal de outras doenças e condições especificadas'],
  ['Z91.1', 'História pessoal de não adesão a tratamento médico'],
  ['Z95.8', 'Presença de outros implantes/enxertos cardíacos e vasculares'],
];

/* ===========================================================
   GRUPOS DE EXAMES por queixa/síndrome neurológica
   Cada grupo tem 'name' e 'exams' (array de {name, specs})
=========================================================== */
window.EXAM_GROUPS = [
  { name: 'Cefaleia primária — investigação básica', exams: [
    { name: 'Ressonância magnética de crânio', specs: 'sem contraste' },
    { name: 'Hemograma completo', specs: '' },
    { name: 'TSH e T4 livre', specs: '' },
    { name: 'PCR e VHS', specs: '' },
  ]},
  { name: 'Cefaleia secundária / atípica', exams: [
    { name: 'Ressonância magnética de crânio', specs: 'com contraste' },
    { name: 'Angiorressonância intracraniana', specs: 'arterial e venosa' },
    { name: 'Angiorressonância de vasos cervicais', specs: '' },
    { name: 'Hemograma, VHS, PCR, TSH', specs: '' },
  ]},
  { name: 'AVC isquêmico — investigação etiológica', exams: [
    { name: 'Ressonância magnética de crânio', specs: 'com sequências DWI/FLAIR' },
    { name: 'Angiorressonância intracraniana e cervical', specs: '' },
    { name: 'Doppler de carótidas e vertebrais', specs: '' },
    { name: 'Doppler transcraniano', specs: '' },
    { name: 'Ecocardiograma transtorácico', specs: 'com Doppler' },
    { name: 'Holter 24h', specs: '' },
    { name: 'ECG de 12 derivações', specs: '' },
    { name: 'Hemograma, glicemia em jejum, HbA1c', specs: '' },
    { name: 'Perfil lipídico (CT, LDL, HDL, TG), Ureia, Creatinina, Sódio, Potássio', specs: '' },
    { name: 'TSH, TGO, TGP, TAP/INR, TTPA', specs: '' },
    { name: 'anti-HIV, VDRL, HBsAg, anti-HCV, Sorologia para Chagas (IGG)', specs: '' },
  ]},
  { name: 'AIT', exams: [
    { name: 'Ressonância magnética de crânio com DWI', specs: '' },
    { name: 'Angiorressonância intracraniana e cervical', specs: '' },
    { name: 'Doppler de carótidas e vertebrais', specs: '' },
    { name: 'Ecocardiograma transtorácico', specs: '' },
    { name: 'ECG e Holter 24h', specs: '' },
    { name: 'Hemograma, glicemia, HbA1c, perfil lipídico', specs: '' },
  ]},
  { name: 'Epilepsia — primeira crise / acompanhamento', exams: [
    { name: 'Eletroencefalograma de rotina', specs: '' },
    { name: 'Ressonância magnética de crânio', specs: 'com protocolo de epilepsia (cortes finos de hipocampo)' },
    { name: 'Hemograma, TGO, TGP, TAP, TTPA, Creatinina, Ureia, Bilirrubinas totais e frações, CPK, Sódio, Potássio', specs: '' },
    { name: 'Dosagem sérica do antiepiléptico', specs: 'se em uso' },
  ]},
  { name: 'Demência / declínio cognitivo', exams: [
    { name: 'Ressonância magnética de crânio', specs: 'com cortes coronais finos do hipocampo' },
    { name: 'TSH, vitamina B12, ácido fólico', specs: '' },
    { name: 'VDRL e anti-HIV', specs: '' },
    { name: 'Hemograma, TGO, TGP, TAP, TTPA, Creatinina, Ureia, Bilirrubinas totais e frações, CPK, Sódio, Potássio, Cálcio', specs: '' },
    { name: 'Avaliação neuropsicológica', specs: '' },
  ]},
  { name: 'Parkinsonismo', exams: [
    { name: 'Ressonância magnética de crânio', specs: '' },
    { name: 'TSH, TGO, TGP, TAP, TTPA, Creatinina, Ureia, Bilirrubinas totais e frações', specs: '' },
    { name: 'Cobre sérico e ceruloplasmina', specs: 'se < 40 anos' },
    { name: 'DAT-SCAN (cintilografia transportador de dopamina)', specs: 'se diagnóstico duvidoso' },
  ]},
  { name: 'Esclerose múltipla / desmielinização', exams: [
    { name: 'Ressonância magnética de encéfalo com contraste', specs: 'protocolo EM' },
    { name: 'Ressonância magnética de medula cervical e torácica', specs: 'com contraste' },
    { name: 'Punção lombar com líquor', specs: 'pesquisa de bandas oligoclonais e IgG' },
    { name: 'Anti-AQP4 e anti-MOG', specs: 'se NMOSD na suspeita' },
    { name: 'Vitamina B12, VDRL, HIV', specs: '' },
  ]},
  { name: 'Vertigem / tontura', exams: [
    { name: 'Audiometria tonal e impedanciometria', specs: '' },
    { name: 'Videonistagmografia (VENG)', specs: '' },
    { name: 'vHIT (head impulse test)', specs: '' },
    { name: 'Ressonância magnética de crânio', specs: 'se sinais centrais' },
    { name: 'Doppler de vertebrais', specs: '' },
  ]},
  { name: 'Polineuropatia periférica', exams: [
    { name: 'Eletroneuromiografia 4 membros', specs: '' },
    { name: 'Glicemia em jejum, HbA1c', specs: '' },
    { name: 'Vitamina B12, ácido fólico', specs: '' },
    { name: 'TSH, TGO, TGP, TAP, TTPA, Creatinina, Ureia, Bilirrubinas totais e frações, CPK, Sódio, Potássio, Cálcio', specs: '' },
    { name: 'Eletroforese de proteínas séricas', specs: '' },
    { name: 'Anti-HIV, VDRL, anti-HCV, HBsAg, anti-HBS', specs: '' },
    { name: 'Cobre, ceruloplasmina, ferritina', specs: '' },
    { name: 'FAN, FR, anti-CCP', specs: '' },
  ]},
  { name: 'Mononeuropatia / radiculopatia', exams: [
    { name: 'Eletroneuromiografia do segmento', specs: '' },
    { name: 'Ressonância magnética da topografia', specs: 'cervical/lombar/etc' },
  ]},
  { name: 'Síndrome do túnel do carpo', exams: [
    { name: 'Eletroneuromiografia bilateral de membros superiores', specs: '' },
    { name: 'USG de nervo mediano', specs: 'se inconclusivo' },
  ]},
  { name: 'Cervicalgia / lombalgia / radiculopatia', exams: [
    { name: 'Ressonância magnética de coluna cervical', specs: '' },
    { name: 'Ressonância magnética de coluna lombar', specs: '' },
    { name: 'Eletroneuromiografia do segmento', specs: 'déficit motor' },
  ]},
  { name: 'Distúrbio do sono', exams: [
    { name: 'Polissonografia tipo I (laboratório)', specs: '' },
    { name: 'Actigrafia 7 dias', specs: ' suspeita de transtorno do ritmo' },
    { name: 'Teste de latências múltiplas (TLMS)', specs: ' suspeita de narcolepsia' },
    { name: 'Ferritina, TSH', specs: ' SPI' },
  ]},
  { name: 'ELA / doença do neurônio motor', exams: [
    { name: 'Eletroneuromiografia 4 membros + paraespinhal + bulbar', specs: '' },
    { name: 'Ressonância magnética de coluna cervical', specs: '' },
    { name: 'Hemograma, CPK, função tireoidiana', specs: '' },
    { name: 'Anti-GM1', specs: '' },
  ]},
  { name: 'Síndrome miastênica', exams: [
    { name: 'Eletroneuromiografia com estimulação repetitiva', specs: '' },
    { name: 'Anti-AChR e anti-MuSK', specs: '' },
    { name: 'TC de tórax (mediastino)', specs: 'pesquisa de timoma' },
    { name: 'TSH', specs: '' },
  ]},
  { name: 'Avaliação pré-anestésica neurológica', exams: [
    { name: 'ECG de 12 derivações', specs: '' },
    { name: 'Hemograma, função renal, eletrólitos, coagulograma', specs: '' },
    { name: 'Glicemia, TSH', specs: '' },
  ]},

  /* ===== Condições clínicas comuns (rotina/comorbidades) ===== */
  { name: 'HAS — rotina anual', exams: [
    { name: 'Hemograma completo', specs: '' },
    { name: 'Glicemia em jejum e HbA1c', specs: '' },
    { name: 'Perfil lipídico', specs: '' },
    { name: 'Função renal (ureia, creatinina)', specs: '' },
    { name: 'Eletrólitos (Na, K)', specs: '' },
    { name: 'EAS / urina tipo 1', specs: '' },
    { name: 'Microalbuminúria em amostra isolada', specs: '' },
    { name: 'TSH', specs: '' },
    { name: 'ECG de 12 derivações', specs: '' },
    { name: 'Ecocardiograma transtorácico', specs: ' HAS estágio 2 ou alvo' },
    { name: 'MAPA 24h', specs: ' HAS resistente / hipertensão do avental branco' },
    { name: 'Fundoscopia', specs: '' },
  ]},
  { name: 'Diabetes mellitus — rotina semestral/anual', exams: [
    { name: 'Glicemia em jejum', specs: '' },
    { name: 'HbA1c (hemoglobina glicada)', specs: '' },
    { name: 'Perfil lipídico (CT, HDL, LDL, TG)', specs: '' },
    { name: 'Função renal (ureia, creatinina, TFG)', specs: '' },
    { name: 'EAS', specs: '' },
    { name: 'Microalbuminúria em amostra isolada', specs: '' },
    { name: 'TSH', specs: '' },
    { name: 'TGO, TGP, GGT', specs: '' },
    { name: 'Hemograma', specs: '' },
    { name: 'ECG de 12 derivações', specs: '' },
    { name: 'Fundoscopia', specs: 'avaliação de retinopatia diabética' },
    { name: 'Avaliação de pé diabético (sensibilidade c/ monofilamento)', specs: '' },
  ]},
  { name: 'Dislipidemia', exams: [
    { name: 'Perfil lipídico (CT, HDL, LDL, TG)', specs: 'em jejum' },
    { name: 'Glicemia em jejum, HbA1c', specs: '' },
    { name: 'TGO, TGP, GGT', specs: '' },
    { name: 'CPK', specs: '' },
    { name: 'TSH', specs: '' },
    { name: 'Função renal', specs: '' },
  ]},
  { name: 'Doença renal crônica', exams: [
    { name: 'Ureia e creatinina (com TFG)', specs: '' },
    { name: 'Eletrólitos (Na, K, Ca, P, Mg)', specs: '' },
    { name: 'Gasometria venosa', specs: '' },
    { name: 'Hemograma completo', specs: '' },
    { name: 'EAS', specs: '' },
    { name: 'Relação proteína/creatinina em amostra isolada', specs: '' },
    { name: 'Microalbuminúria', specs: '' },
    { name: 'PTH intacto', specs: '' },
    { name: '25-hidroxivitamina D', specs: '' },
    { name: 'USG de rins e vias urinárias', specs: '' },
  ]},
  { name: 'Função tireoidiana', exams: [
    { name: 'TSH', specs: '' },
    { name: 'T4 livre', specs: '' },
    { name: 'Anti-TPO e anti-tireoglobulina', specs: ' TSH alterado' },
    { name: 'USG de tireoide', specs: 'se nódulo palpável ou TSH alterado' },
  ]},
  { name: 'Anemia — investigação inicial', exams: [
    { name: 'Hemograma completo com reticulócitos', specs: '' },
    { name: 'Ferritina, ferro sérico, TIBC, saturação de transferrina', specs: '' },
    { name: 'Vitamina B12 e ácido fólico', specs: '' },
    { name: 'TSH', specs: '' },
    { name: 'LDH, bilirrubinas, haptoglobina, Coombs direto', specs: 'se suspeita de hemólise' },
    { name: 'Função renal e hepática', specs: '' },
    { name: 'EAS / pesquisa de sangue oculto nas fezes', specs: '' },
  ]},
  { name: 'Avaliação cardiovascular geral', exams: [
    { name: 'ECG de 12 derivações', specs: '' },
    { name: 'Ecocardiograma transtorácico com Doppler', specs: '' },
    { name: 'Holter 24h', specs: '' },
    { name: 'MAPA 24h', specs: '' },
    { name: 'Teste ergométrico', specs: 'se indicação' },
    { name: 'Perfil lipídico, glicemia, HbA1c', specs: '' },
  ]},
  { name: 'Check-up clínico geral (homem ≥40a)', exams: [
    { name: 'Hemograma completo', specs: '' },
    { name: 'Glicemia em jejum, HbA1c', specs: '' },
    { name: 'Perfil lipídico', specs: '' },
    { name: 'Função renal (ureia, creatinina, TFG)', specs: '' },
    { name: 'TGO, TGP, GGT, FA, bilirrubinas', specs: '' },
    { name: 'TSH', specs: '' },
    { name: 'Vitamina D, vitamina B12', specs: '' },
    { name: 'Ácido úrico', specs: '' },
    { name: 'EAS', specs: '' },
    { name: 'Pesquisa de sangue oculto nas fezes', specs: '' },
    { name: 'PSA total', specs: 'após orientação' },
    { name: 'ECG de 12 derivações', specs: '' },
    { name: 'USG abdome total', specs: '' },
    { name: 'Radiografia de tórax', specs: '' },
  ]},
  { name: 'Check-up clínico geral (mulher ≥40a)', exams: [
    { name: 'Hemograma completo', specs: '' },
    { name: 'Glicemia em jejum, HbA1c', specs: '' },
    { name: 'Perfil lipídico', specs: '' },
    { name: 'Função renal (ureia, creatinina, TFG)', specs: '' },
    { name: 'TGO, TGP, GGT, FA, bilirrubinas', specs: '' },
    { name: 'TSH', specs: '' },
    { name: 'Vitamina D, vitamina B12', specs: '' },
    { name: 'Ácido úrico', specs: '' },
    { name: 'EAS', specs: '' },
    { name: 'Pesquisa de sangue oculto nas fezes', specs: '' },
    { name: 'Mamografia bilateral', specs: '' },
    { name: 'USG transvaginal e mamas', specs: '' },
    { name: 'Citopatológico de colo uterino', specs: '' },
    { name: 'Densitometria óssea', specs: 'após menopausa' },
    { name: 'ECG de 12 derivações', specs: '' },
    { name: 'USG abdome total', specs: '' },
  ]},
  { name: 'Síndrome metabólica', exams: [
    { name: 'Glicemia em jejum, HbA1c, curva glicêmica', specs: '' },
    { name: 'Perfil lipídico', specs: '' },
    { name: 'TGO, TGP, GGT', specs: '' },
    { name: 'Ácido úrico', specs: '' },
    { name: 'Insulina basal e HOMA-IR', specs: '' },
    { name: 'TSH', specs: '' },
    { name: 'USG abdome (esteatose hepática)', specs: '' },
  ]},
  { name: 'Hepatopatia / esteatose', exams: [
    { name: 'TGO, TGP, GGT, FA, bilirrubinas', specs: '' },
    { name: 'Albumina e proteínas totais', specs: '' },
    { name: 'TP/INR', specs: '' },
    { name: 'Sorologias HBV/HCV/HIV', specs: '' },
    { name: 'Ferritina, saturação de transferrina', specs: '' },
    { name: 'Anti-mitocôndria, anti-músculo liso, anti-LKM', specs: ' autoimune' },
    { name: 'USG abdome superior com Doppler', specs: '' },
    { name: 'Elastografia hepática', specs: 'se fibrose suspeita' },
  ]},
];

/* ===========================================================
   CATÁLOGO geral de exames disponíveis (para autocomplete)
=========================================================== */
window.EXAM_CATALOG = [
  // --- Imagem do SNC
  'Tomografia computadorizada de crânio sem contraste',
  'Tomografia computadorizada de crânio com contraste',
  'AngioTC intracraniana e de vasos cervicais',
  'Ressonância magnética de crânio sem contraste',
  'Ressonância magnética de crânio com contraste',
  'Ressonância magnética de crânio com sequências DWI/PWI',
  'Ressonância magnética de crânio com protocolo de epilepsia',
  'Ressonância magnética de crânio com protocolo de esclerose múltipla',
  'Ressonância magnética de crânio com tractografia',
  'Ressonância magnética funcional do encéfalo (RMf)',
  'Espectroscopia por ressonância magnética',
  'Angiorressonância intracraniana arterial',
  'Angiorressonância intracraniana venosa',
  'Angiorressonância de vasos cervicais',
  'Arteriografia cerebral digital',
  'Mielografia',
  // --- Imagem da coluna
  'Ressonância magnética de coluna cervical',
  'Ressonância magnética de coluna torácica',
  'Ressonância magnética de coluna lombossacra',
  'Tomografia computadorizada de coluna cervical',
  'Tomografia computadorizada de coluna lombar',
  'Radiografia de coluna cervical AP/perfil',
  'Radiografia de coluna lombossacra AP/perfil',
  'Radiografia de coluna lombar dinâmica (flexão/extensão)',
  // --- Doppler / vasculares
  'Doppler de carótidas e vertebrais',
  'Doppler transcraniano',
  // --- Eletrofisiologia
  'Eletroencefalograma (EEG) de rotina',
  'EEG com privação de sono',
  'EEG prolongado',
  'Vídeo-EEG',
  'Eletroneuromiografia (ENMG) de membros superiores',
  'Eletroneuromiografia (ENMG) de membros inferiores',
  'Eletroneuromiografia (ENMG) de quatro membros',
  'Eletroneuromiografia com estimulação repetitiva',
  'Potencial evocado visual (PEV)',
  'Potencial evocado auditivo de tronco (PEATE/BERA)',
  'Potencial evocado somatossensitivo (PESS)',
  'Potencial evocado motor (PEM)',
  // --- Otoneurológicos
  'Audiometria tonal e vocal',
  'Imitanciometria / impedanciometria',
  'Videonistagmografia (VENG)',
  'Vídeo head impulse test (vHIT)',
  'Posturografia dinâmica',
  // --- Sono
  'Polissonografia tipo I (laboratório)',
  'Polissonografia tipo III (domiciliar)',
  'Actigrafia',
  'Teste de latências múltiplas do sono (TLMS)',
  'Teste de manutenção da vigília',
  // --- Líquor / punção
  'Punção lombar diagnóstica',
  'Análise citológica e bioquímica do líquor',
  'Pesquisa de bandas oligoclonais no líquor',
  'IgG no líquor (índice de Link)',
  'Pesquisa de PCR viral no líquor',
  // --- Cardiológicos
  'ECG de 12 derivações',
  'Holter 24h',
  'MAPA 24h',
  'Ecocardiograma transtorácico',
  'Ecocardiograma transesofágico',
  // --- Laboratório geral
  'Hemograma completo',
  'VHS',
  'PCR ultrassensível',
  'Glicemia em jejum',
  'HbA1c (hemoglobina glicada)',
  'Curva glicêmica',
  'Perfil lipídico (Colesterol total, HDL, LDL, Triglicerideos)',
  'Função renal (ureia, creatinina)',
  'Eletrólitos (Na, K, Cl, Mg, Ca, P)',
  'Sodio',
  'Potassio',
  'Magnesio',
  'Calcio ionizado',
  'Função hepática (TGO, TGP, GGT, FA, Bilirrubinas totais e frações)',
  'Coagulograma (TAP/INR, TTPA)',
  'EAS / urina tipo 1',
  'TSH e T4 livre',
  'Vitamina B12',
  'Ácido fólico',
  'Vitamina D (25-OH)',
  '25-hidroxivitamina D',
  'Cobre sérico',
  'Ceruloplasmina',
  'Ferritina, ferro sérico, TIBC',
  'Eletroforese de proteínas séricas',
  'Imunofixação sérica',
  // --- Imuno / autoanticorpos
  'FAN (fator antinuclear)',
  'Fator reumatoide',
  'Anti-CCP',
  'Anti-DNA',
  'Anti-Ro/La',
  'Anti-aquaporina 4 (anti-AQP4)',
  'Anti-MOG',
  'Anti-receptor de acetilcolina (anti-AChR)',
  'Anti-MuSK',
  'Anti-GM1',
  'Anticorpos anti-gangliosídeos',
  'Anticardiolipina IgG/IgM',
  'Anti-β2-glicoproteína I',
  'Anticoagulante lúpico',
  // --- Sorológicos
  'Anti-HIV 1/2',
  'VDRL',
  'FTA-Abs',
  'Anti-HCV',
  'HBsAg, anti-HBc, anti-HBs',
  // --- Outros
  'Tomografia de tórax (mediastino) — pesquisa de timoma',
  'DAT-SCAN (cintilografia de transportador de dopamina)',
  'PET-CT cerebral com FDG',
  'PET-CT cerebral com amiloide',
  'Avaliação neuropsicológica',
  'Mini-Exame do Estado Mental (MEEM)',
  'MoCA (Montreal Cognitive Assessment)',
  'Biópsia muscular',
  'Biópsia de nervo sural',
  'Biópsia de pele para densidade de fibras finas',
];
